[workspace]
publish = false
release = false
git_release_enable = false
changelog_config = "cliff.toml"
changelog_update = false

[[package]]
name = "edc-dataplane-core"
changelog_path = "crates/dataplane-core/CHANGELOG.md"
publish = true
release = true
git_release_enable = true
changelog_update = true
git_tag_enable = true

[[package]]
name = "edc-dataplane"
changelog_path = "crates/dataplane/CHANGELOG.md"
publish = true
release = true
git_release_enable = false
changelog_update = true
git_tag_enable = true

[[package]]
name = "edc-dataplane-signaling"
publish = true
release = true
git_release_enable = true
changelog_path = "crates/dataplane-signaling/CHANGELOG.md"
changelog_update = true
git_tag_enable = true
