name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release-plz/*

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
    steps:
      - uses: actions/checkout@v2
      - name: Starting EDC Servers
        run: |
          export CONNECTOR_IMAGE=ghcr.io/dataspace-rs/control-plane:latest
          docker compose -f ./testing/docker-compose.yml up -d

      - uses: actions/checkout@v2
      - name: Install latest ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          components: rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all -- -D warnings
      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Run cargo test with nextest
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run
